package com.example.glyph_glance.logic

/**
 * Returns the embedded semantic keywords JSON.
 * This is loaded at compile time and available across all platforms.
 * 
 * The JSON contains keywords and phrases that affect notification urgency scoring.
 * Each keyword has:
 * - text: The phrase to match (case-insensitive)
 * - level: Urgency level 1-6
 * - category: Category for grouping (safety, security, health, etc.)
 */
fun getSemanticKeywordsJson(): String = """
{
  "version": 1,
  "description": "Semantic keywords and phrases that affect notification urgency scoring",
  "semantics": [
    {"text": "call 911", "level": 6, "category": "safety"},
    {"text": "help me", "level": 6, "category": "safety"},
    {"text": "hospital", "level": 6, "category": "safety"},
    {"text": "emergency room", "level": 6, "category": "safety"},
    {"text": "ambulance", "level": 6, "category": "safety"},
    {"text": "fire", "level": 6, "category": "safety"},
    {"text": "police", "level": 6, "category": "safety"},
    {"text": "accident", "level": 6, "category": "safety"},
    {"text": "injured", "level": 6, "category": "safety"},
    {"text": "bleeding", "level": 6, "category": "safety"},
    {"text": "unconscious", "level": 6, "category": "safety"},
    {"text": "heart attack", "level": 6, "category": "safety"},
    {"text": "stroke", "level": 6, "category": "safety"},
    {"text": "choking", "level": 6, "category": "safety"},
    {"text": "security alert", "level": 6, "category": "security"},
    {"text": "unauthorized access", "level": 6, "category": "security"},
    {"text": "verification code", "level": 6, "category": "security"},
    {"text": "your otp is", "level": 6, "category": "security"},
    {"text": "break in", "level": 6, "category": "security"},
    {"text": "intruder", "level": 6, "category": "security"},
    {"text": "login attempt", "level": 5, "category": "security"},
    {"text": "suspicious login", "level": 5, "category": "security"},
    {"text": "fraud alert", "level": 6, "category": "finance"},
    {"text": "transaction declined", "level": 5, "category": "finance"},
    {"text": "payment failed", "level": 5, "category": "finance"},
    {"text": "overdraft", "level": 5, "category": "finance"},
    {"text": "suspicious activity", "level": 6, "category": "finance"},
    {"text": "identity theft", "level": 6, "category": "finance"},
    {"text": "account frozen", "level": 5, "category": "finance"},
    {"text": "deadline", "level": 5, "category": "work"},
    {"text": "asap", "level": 5, "category": "work"},
    {"text": "urgent", "level": 5, "category": "general"},
    {"text": "immediately", "level": 5, "category": "general"},
    {"text": "right now", "level": 5, "category": "general"},
    {"text": "production down", "level": 6, "category": "work"},
    {"text": "server crash", "level": 6, "category": "work"},
    {"text": "system outage", "level": 6, "category": "work"},
    {"text": "critical error", "level": 6, "category": "work"},
    {"text": "meeting starting", "level": 4, "category": "work"},
    {"text": "where are you", "level": 4, "category": "social"},
    {"text": "pick up", "level": 5, "category": "family"},
    {"text": "school called", "level": 5, "category": "family"},
    {"text": "teacher", "level": 4, "category": "family"},
    {"text": "doctor", "level": 5, "category": "health"},
    {"text": "appointment", "level": 4, "category": "health"},
    {"text": "alarm", "level": 6, "category": "home"},
    {"text": "motion detected", "level": 5, "category": "home"},
    {"text": "camera", "level": 5, "category": "home"},
    {"text": "leak", "level": 6, "category": "home"},
    {"text": "doorbell", "level": 4, "category": "home"},
    {"text": "smoke detector", "level": 6, "category": "home"},
    {"text": "carbon monoxide", "level": 6, "category": "home"},
    {"text": "delivery here", "level": 4, "category": "delivery"},
    {"text": "driver outside", "level": 5, "category": "delivery"},
    {"text": "your food", "level": 4, "category": "delivery"},
    {"text": "package arrived", "level": 4, "category": "delivery"},
    {"text": "flight cancelled", "level": 6, "category": "travel"},
    {"text": "gate change", "level": 5, "category": "travel"},
    {"text": "boarding now", "level": 5, "category": "travel"},
    {"text": "delay", "level": 4, "category": "travel"},
    {"text": "missed flight", "level": 6, "category": "travel"},
    {"text": "passport issue", "level": 6, "category": "travel"},
    {"text": "battery low", "level": 3, "category": "system"},
    {"text": "update available", "level": 2, "category": "system"},
    {"text": "storage full", "level": 4, "category": "system"},
    {"text": "sale", "level": 2, "category": "marketing"},
    {"text": "discount", "level": 2, "category": "marketing"},
    {"text": "offer", "level": 2, "category": "marketing"},
    {"text": "newsletter", "level": 1, "category": "marketing"},
    {"text": "subscribe", "level": 1, "category": "marketing"},
    {"text": "promotion", "level": 2, "category": "marketing"},
    {"text": "liked your message", "level": 1, "category": "social"},
    {"text": "reacted to", "level": 1, "category": "social"},
    {"text": "sent a photo", "level": 3, "category": "social"},
    {"text": "call me", "level": 5, "category": "social"},
    {"text": "we need to talk", "level": 5, "category": "social"},
    {"text": "important news", "level": 5, "category": "social"},
    {"text": "family emergency", "level": 6, "category": "family"},
    {"text": "car broke down", "level": 5, "category": "transportation"},
    {"text": "flat tire", "level": 5, "category": "transportation"},
    {"text": "out of gas", "level": 4, "category": "transportation"},
    {"text": "power outage", "level": 5, "category": "home"},
    {"text": "water shutoff", "level": 4, "category": "home"},
    {"text": "prescription ready", "level": 4, "category": "health"},
    {"text": "test results", "level": 5, "category": "health"},
    {"text": "weather alert", "level": 5, "category": "environment"},
    {"text": "storm warning", "level": 6, "category": "environment"},
    {"text": "evacuation", "level": 6, "category": "environment"},
    {"text": "reminder", "level": 3, "category": "general"},
    {"text": "sent a reel", "level": 1, "category": "social"},
    {"text": "follow up", "level": 3, "category": "work"},
    {"text": "status update", "level": 3, "category": "work"},
    {"text": "just checking in", "level": 2, "category": "social"},
    {"text": "thinking of you", "level": 2, "category": "social"},
    {"text": "new upload", "level": 1, "category": "social"},
    {"text": "good morning", "level": 1, "category": "social"},
    {"text": "good night", "level": 1, "category": "social"},
    {"text": "live now", "level": 3, "category": "social"},
    {"text": "going live", "level": 3, "category": "social"},
    {"text": "trending", "level": 2, "category": "social"},
    {"text": "viral", "level": 2, "category": "social"},
    {"text": "tagged you", "level": 3, "category": "social"},
    {"text": "mentioned you", "level": 3, "category": "social"},
    {"text": "voice message", "level": 3, "category": "social"},
    {"text": "voice note", "level": 3, "category": "social"},
    {"text": "video call", "level": 4, "category": "social"},
    {"text": "missed call", "level": 3, "category": "social"},
    {"text": "group chat", "level": 3, "category": "social"},
    {"text": "added to group", "level": 3, "category": "social"},
    {"text": "hacked", "level": 6, "category": "security"},
    {"text": "password changed", "level": 4, "category": "security"},
    {"text": "login from new device", "level": 4, "category": "security"},
    {"text": "unusual activity", "level": 5, "category": "security"},
    {"text": "account suspended", "level": 5, "category": "security"},
    {"text": "active shooter", "level": 6, "category": "safety"},
    {"text": "hostage situation", "level": 6, "category": "safety"},
    {"text": "bomb threat", "level": 6, "category": "security"},
    {"text": "terrorist attack", "level": 6, "category": "security"},
    {"text": "explosion", "level": 6, "category": "safety"},
    {"text": "gas leak", "level": 6, "category": "home"},
    {"text": "electrical fire", "level": 6, "category": "home"},
    {"text": "structural collapse", "level": 6, "category": "safety"},
    {"text": "trapped", "level": 6, "category": "safety"},
    {"text": "can't breathe", "level": 6, "category": "health"},
    {"text": "seizure", "level": 6, "category": "health"},
    {"text": "allergic reaction", "level": 6, "category": "health"},
    {"text": "anaphylaxis", "level": 6, "category": "health"},
    {"text": "overdose", "level": 6, "category": "health"},
    {"text": "poisoning", "level": 6, "category": "health"},
    {"text": "suicide threat", "level": 6, "category": "mental health"},
    {"text": "self harm", "level": 6, "category": "mental health"},
    {"text": "mental breakdown", "level": 5, "category": "mental health"},
    {"text": "panic attack", "level": 5, "category": "mental health"},
    {"text": "child missing", "level": 6, "category": "family"},
    {"text": "elderly missing", "level": 6, "category": "family"},
    {"text": "kidnapping", "level": 6, "category": "safety"},
    {"text": "abduction", "level": 6, "category": "safety"},
    {"text": "domestic violence", "level": 6, "category": "safety"},
    {"text": "assault", "level": 6, "category": "safety"},
    {"text": "home invasion", "level": 6, "category": "security"},
    {"text": "tsunami warning", "level": 6, "category": "environment"},
    {"text": "tornado warning", "level": 6, "category": "environment"},
    {"text": "hurricane landfall", "level": 6, "category": "environment"},
    {"text": "earthquake", "level": 6, "category": "environment"},
    {"text": "flash flood", "level": 6, "category": "environment"},
    {"text": "wildfire", "level": 6, "category": "environment"},
    {"text": "volcanic eruption", "level": 6, "category": "environment"},
    {"text": "avalanche", "level": 6, "category": "environment"},
    {"text": "nuclear meltdown", "level": 6, "category": "environment"},
    {"text": "chemical spill", "level": 6, "category": "environment"},
    {"text": "radiation leak", "level": 6, "category": "environment"},
    {"text": "biohazard", "level": 6, "category": "environment"},
    {"text": "pandemic outbreak", "level": 6, "category": "health"},
    {"text": "quarantine order", "level": 5, "category": "health"},
    {"text": "data breach", "level": 6, "category": "security"},
    {"text": "ransomware attack", "level": 6, "category": "security"},
    {"text": "critical system failure", "level": 6, "category": "work"},
    {"text": "train derailment", "level": 6, "category": "transportation"},
    {"text": "plane crash", "level": 6, "category": "transportation"},
    {"text": "mayday", "level": 6, "category": "transportation"},
    {"text": "sos", "level": 6, "category": "general"},
    {"text": "distress signal", "level": 6, "category": "general"},
    {"text": "life threatening", "level": 6, "category": "health"},
    {"text": "critical condition", "level": 6, "category": "health"},
    {"text": "code blue", "level": 6, "category": "health"},
    {"text": "cardiac arrest", "level": 6, "category": "health"},
    {"text": "drowning", "level": 6, "category": "safety"},
    {"text": "hypothermia", "level": 6, "category": "health"},
    {"text": "heat stroke", "level": 6, "category": "health"},
    {"text": "electrocution", "level": 6, "category": "safety"},
    {"text": "head trauma", "level": 6, "category": "health"},
    {"text": "stabbing", "level": 6, "category": "safety"},
    {"text": "mass casualty", "level": 6, "category": "safety"},
    {"text": "war zone", "level": 6, "category": "security"},
    {"text": "famine", "level": 6, "category": "humanitarian"},
    {"text": "epidemic", "level": 6, "category": "health"},
    {"text": "plague", "level": 6, "category": "health"},
    {"text": "outbreak", "level": 6, "category": "health"}
  ]
}
""".trimIndent()

